### ISSUE TITLE
Add Toroidal Wrap Around for LineGraphics

### ISSUE THREAD

**Issue by matthewCmatt** [amymcgovern/spacesettlers#37]
Current implementation does not wrap line graphics around the edges of the canvas.

Implement toroidal wraparound using the existing methods used by, for instance, ShipGraphics.
Do not implement the wraparound within the LineGraphics class.

**Comment by amymcgovern** [comment]
Feel free to implement it and get the extra credit for it!

**Comment by matthewCmatt** [comment]
PR created: https://github.com/amymcgovern/spacesettlers/pull/38

**Comment by amymcgovern** [comment]
Accepted (thank you!)
